version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/code-inside-project
    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=User19cfb4
      - POSTGRES_DB=code-inside-project
    ports:
      - "5000:5432"
    restart: always