version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/code-inside-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: User19cfb4
    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=User19cfb4
      - POSTGRES_DB=code-inside-project
    volumes:
      - db:/var/lib/postgresql/data

    ports:
      - "5000:5432"
    restart: always

volumes:
  db:
